"""Default config keys for TAMS. Merged after YAML load for sensible defaults."""

DEFAULT_KEYS = {
    "split": None,
    "model_name": "TAMS",
    "task_mode": "generic",
    "score_level": "frame",
    "protocol_mode": "strict_main",
    "monitor_metric": "loss",
    "output_adapter": "none",
    "modalities": ["v"],
    "use_query": False,
    "use_step0": False,
    "use_spf": False,
    "use_ref": False,
    "step0_cache_json": None,
    "step0_multimodal_json": None,
    "apply_modality_scale": False,
    "step0_default_confidence": 1.0,
    "use_m4_head": False,
    "m4_confidence_gating": False,
    "m4_hidden_dim": 0,
    "plan_wire_m1": False,
    "m1_use_missing_token": False,
    "plan_wire_m3": False,
    "use_text": False,
    "use_audio": False,
    "use_rank_loss": False,
    "use_query_loss": False,
    "fusion_type": "none",
    "m2_visual_type": "thres",
    "m2_text_type": "sage",
    "m2_audio_type": "sage",
    "tau1_init": 0.2,
    "tau2_init": 0.5,
    "lambda_rank": 0.1,
    "lambda_q": 0.1,
    "lambda_gate": 0.0,
    "lambda_top": 0.0,
    "device": "cuda:0",
    "seed": 42,
    "monitor_joint_w_f1": 1.0,
    "monitor_joint_w_tau": 0.2,
    "monitor_joint_w_rho": 0.2,
    "joint_val_budget": 0.15,
    "joint_use_f1_proxy": True,
    "rank_pairs_per_video": 32,
    "rank_supervision": "pseudo",
    "root_data": "./data",
    "root_result": "./results",
    "query_encoder": "none",
    "query_bridge": "global_node",
    "query_fusion": "bridge",
    "query_cross_attn_heads": 4,
    "query_cross_attn_dropout": 0.1,
    "qfvs_annotations": "annotations/QFVS",
    "qfvs_sharghi_top_frac": 0.02,
    "qfvs_sharghi_top_frac_by_split": None,
    "videoxum_fea": "blip",
    "videoxum_audio_feature_dir": None,
    "videoxum_audio_fallback": "error",
    "videoxum_modality_dim": None,
    "videoxum_modality_dropout_p": 0.0,
    "videoxum_modality_dropout_which": "aux",
    "mrhisum_root": None,
    "mrhisum_eval_fps": 1.0,
    "mrhisum_hl_shot_seconds": 5.0,
    "mrhisum_dataloader_num_workers": 4,
    "mrhisum_dataloader_pin_memory": True,
    "mrhisum_modality_dropout_p": 0.0,
    "mrhisum_modality_dropout_which": "aux",
    "mrhisum_cosine_t_max": None,
    "qfvs_dataloader_num_workers": 0,
    "qfvs_dataloader_pin_memory": True,
    "stvs_dataloader_num_workers": 0,
    "stvs_dataloader_pin_memory": True,
    "qfvs_cosine_t_max": None,
    "mrhisum_no_pad": False,
    "modality_dims": None,
    "interleaved_layers": 0,
    "multi_scale_taus": None,
    "cmf_n_heads": 4,
    "use_mean_sum": True,
    "tau": 2,
    "use_amp": True,
    "gradient_checkpointing": False,
    "disable_dual_threshold": False,
    "use_matl": False,
    "use_ta_gnn": False,
    "use_tbcmi": False,
    "use_tgmi": False,
    "matl_scales": [3, 10, 30],
    "matl_temperature_init": 1.0,
    "matl_temperature_final": 0.1,
    "matl_temperature_epochs": 15,
    "lambda_topo_sparse": 0.01,
    "lambda_topo_div": 0.005,
    "topo_rho_min": 0.3,
    "tbcmi_n_heads": 4,
    "tbcmi_dropout": 0.1,
    "matl_freeze_epochs": 0,
    "use_ot_cma": False,
    "sinkhorn_reg": 0.1,
    "sinkhorn_iter": 8,
    "ot_cma_topo_weight": 0.1,
    "ot_cma_dropout": 0.1,
    "use_directional_gnn": False,
    "use_modality_gate": False,
}


def merge_defaults(cfg: dict) -> dict:
    for k, v in DEFAULT_KEYS.items():
        if k not in cfg or cfg[k] is None:
            cfg[k] = v
    return cfg
